### ISSUE TITLE
Unhandled Exception: type 'List<Grouping<dynamic, dynamic>>' is not a subtype

### ISSUE THREAD

**Issue by Katekko** [andrewackerman/darq#3]
![image](https://user-images.githubusercontent.com/13632735/90701111-f6487100-e25d-11ea-81b4-055d566917f6.png)

I really don't know what I'am doing wrong...

Any clue?

All stacktrace below
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'List<Grouping<dynamic, dynamic>>' is not a subtype of type 'List<Grouping<int, FaturamentoModel>>'
E/flutter (28357): #0      Lookup.resizeBuffer 
package:darq/src/lookup.dart:160
E/flutter (28357): #1      Lookup.getGrouping 
package:darq/src/lookup.dart:125
E/flutter (28357): #2      Lookup.create 
package:darq/src/lookup.dart:36
E/flutter (28357): #3      GroupByIterable.iterator 
package:darq/…/iterables/group_by_iterable.dart:14
E/flutter (28357): #4      MappedIterable.iterator  (dart:_internal/iterable.dart:364:66)
E/flutter (28357): #5      new List.from  (dart:core-patch/array_patch.dart:50:19)
E/flutter (28357): #6      new List.of  (dart:core-patch/array_patch.dart:68:17)
E/flutter (28357): #7      Iterable.toList  (dart:core/iterable.dart:404:12)
E/flutter (28357): #8      RelatorioHelper.montarRelatoriosClientes 
package:arctekko/…/helpers/relatorio.helper.dart:148
E/flutter (28357): #9      FaturamentoSubModuloController.loadRelatorioClientes 
package:arctekko/…/faturamento_sub_modulo/faturamento_sub_modulo.controller.dart:223
E/flutter (28357): #10     ever.<anonymous closure> 
package:get/…/rx/rx_event.dart:9
E/flutter (28357): #11     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (28357): #12     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (28357): #13     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter (28357): #14     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)
E/flutter (28357): #15     _DelayedData.perform  (dart:async/stream_impl.dart:611:14)
E/flutter (28357): #16     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:730:11)
E/flutter (28357): #17     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:687:7)
E/flutter (28357): #18     _rootRun  (dart:async/zone.dart:1182:47)
E/flutter (28357): #19     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (28357): #20     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (28357): #21     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (28357): #22     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (28357): #23     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (28357): #24     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (28357): #25     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (28357): #26     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (28357): #27     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
E/flutter (28357):
```

**Comment by Miiite** [comment]
I have the same issue with using the "groupBy" method on my side. I have to check the repos unit tests to try to understand what's going on here

**Comment by andrewackerman** [comment]
I have accepted Miiite's pull request on this issue.
